openapi: 3.1.0
info:
  title: Swagger API - Match service
  version: 1.0.0
schemes:
  - http
  - https
paths:
  /api/match:
    get:
      summary: Get all matches
      tags:
        - Match
      responses:
        '200':
          description: List of matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
  /api/match/user:
    get:
      summary: Get matches for a user
      tags:
        - Match
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: string
          description: The ID of the user
      responses:
        '200':
          description: List of user matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
  /api/match/{id}:
    delete:
      summary: Delete a match
      tags:
        - Match
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The match ID
      responses:
        '200':
          description: Match deleted
        '404':
          description: Match not found
components:
  schemas:
    Match:
      type: object
      properties:
        id:
          type: number
          description: Unique identifier for the match
        userId:
          type: number
          description: User Id of the match
      required:
        - id
      example:
        id: 1
        userId: 1
tags:
  - name: Match
    description: Opérations sur les matchs
